# Generated by Django 5.1.3 on 2024-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название бизнеса')),
                ('business_type', models.CharField(max_length=200, verbose_name='Тип бизнеса')),
                ('region', models.CharField(max_length=200, verbose_name='Регион')),
                ('industry', models.CharField(max_length=200, verbose_name='Отрасль бизнеса')),
                ('is_innovative', models.BooleanField(verbose_name='Есть ли инновации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользовательские данные',
                'ordering': ['-updated_at'],
            },
        ),
    ]
