# Generated by Django 5.1.3 on 2024-11-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип бизнеса'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Отрасль бизнеса'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='is_innovative',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть ли инновации'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Регион'),
        ),
    ]
