# Generated by Django 5.1.3 on 2024-11-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_datafromsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafromsite',
            name='user_data',
        ),
    ]
