# Generated by Django 5.1.3 on 2024-11-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_datafromsite_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Сгенерированный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdata', verbose_name='Пользовательские данные')),
            ],
            options={
                'verbose_name': 'Сгенерированные данные',
            },
        ),
    ]
